### ISSUE TITLE
META join

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#719]
A place for collecting all of the join thoughts.

Things that join should probably be able to do:
- [x] Join only the shared channels and variables while discarding the rest
- [x] Join overlapping and grid-aligned data
- [x] Join overlapping and non-grid aligned data
- [x] pass the test of `join(x, y, 'first')` being the same as `join(y, x, 'last')` 
- [x] Join 1D slices with 2D planes
- [x] Join 2D planes with 3D boxes
- [x] Join non-overlapping data, grid-aligned data 
- [x] Join non-overlapping, non-grid-aligned data
- [x] Join overlapped and non-overlapped boxes
- [x] Join 3+ data of varying dimension all at the same time
- [x] Pass tests for all of the above
- [x] Join all split tests. Including: http://wright.tools/en/development/auto_examples/split.html#sphx-glr-auto-examples-split-py 

Things that join should maybe be able to do:
- [ ] Join n dimensional data with m dimensional data intersecting at arbitrary skew

**Comment by darienmorrow** [comment]
Related issues:
#592 #508 #507 #504 #503

**Comment by ksunden** [comment]
Note, I do not explicitly test joining the gallery example, but I do test joining the split tests we had in the tests directory (Which test the same concepts)

**Comment by ksunden** [comment]
Arbitrary skew _may_ work, but only if it can be transformed to 1D axes that match the 3D data, did not write a test for it, as I do not have a usecase in mind
